---
# Source: realworld/templates/jenkins.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  annotations:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/the9thlime/realworldtt/'
    targetRevision: feat/helm-chart # Happy case
    path: add-ons/jenkins
    helm:
      value:
        installPlugins:
          - kubernetes:4253.v7700d91739e5
          - workflow-aggregator:600.vb_57cdd26fdd7
          - git:5.2.2
          - configuration-as-code:1836.vccda_4a_122a_a_e
          - docker-workflow:580.vc0c340686b_54
  destination:
    name: ''
    namespace: devops-tools
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Source: realworld/templates/mysql.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  annotations:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/the9thlime/realworldtt.git
    targetRevision: feat/helm-chart
    path: add-ons/mysql
    helm:
      values: |
        mysql:
        
          auth:
            createDatabase: false
            rootPassword: "123"
          initdbScripts:
            init.sql: |
              CREATE DATABASE realworld;
              CREATE USER 'realworld'@'%' IDENTIFIED BY '123';
              GRANT ALL PRIVILEGES ON realworld.* TO 'realworld'@'%';
              GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
              FLUSH PRIVILEGES;
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
---
# Source: realworld/templates/realworld.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realworld
  annotations:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/the9thlime/realworldtt.git
    targetRevision: feat/helm-chart
    path: manifests/
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
