##############################
# Global values
##############################

repoURL: https://github.com/the9thlime/realworldtt.git

###############################
# ArgoCD
###############################

argocd:
  namespace:

###############################
# Realworld app
###############################

realworld:
  syncwave:
  namespace:

###############################
# MySQL
###############################

mysql:
  rootPassword: 123
  realworldUserPassword: 123
  syncwave:
  namespace:
  values:


###############################
# Jenkins
###############################

jenkins:
  enabled: true
  syncwave:
  namespace:

