apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
<<<<<<< HEAD
  namespace: {{ .Values.mysql.namespaceOverride}}
=======
>>>>>>> 24eede954a135f9ec46abfcdb84ec964c50fd566
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS realworld;
    CREATE USER IF NOT EXISTS '{{ .Values.mysql.adminUsername }}'@'%' IDENTIFIED BY '{{ .Values.mysql.adminPassword }}';
    GRANT ALL PRIVILEGES ON realworld.* TO '{{ .Values.mysql.adminUsername }}'@'%';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
