apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworldtt-deployment
  namespace: {{ .Values.realworld.namespace}}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: realworldtt
    app.kubernetes.io/part-of: realworldtt
    app.kubernetes.io/version: 0.0.6
    app.kubernetes.io/component: deployment
spec:
  replicas: {{ .Values.realworld.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: realworldtt
        app.kubernetes.io/version: 0.0.6
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: realworldtt
          image: the9thlime/realworldtt:0.0.6
          ports:
            - containerPort: 8000
          resources:
            {{ with .Values.realworld.app}}
            limits:
              {{- range $key, $value := .limits }}
              {{ $key }}: {{ $value}}
              {{- end}}
            requests:
              {{- range $key, $value := .requests }}
              {{ $key }}: {{ $value}}
              {{- end}}
            {{- end }}
          envFrom:
            - secretRef:
                name: django-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mysql.namespaceOverride}}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.realworld.namespace}}