<<<<<<< HEAD
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: {{ .Values.realworld.namespace }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.realworld.secrets.SECRET_KEY | printf "%v" | b64enc }}
  DATABASE_NAME: {{ .Values.realworld.secrets.DATABASE_NAME | printf "%v" | b64enc }}
  DATABASE_USER: {{ .Values.mysql.adminUsername | printf "%v" | b64enc }}
  DATABASE_PASSWORD: {{ .Values.mysql.adminPassword |  printf "%v" | b64enc }}
  DATABASE_HOST: {{ printf "%s-mysql.%s.svc.cluster.local" .Release.Name .Values.mysql.namespaceOverride | b64enc }}
  DATABASE_PORT: {{ .Values.realworld.secrets.DATABASE_PORT | printf "%v" | b64enc }}
=======
{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: django-secrets*/}}
{{/*  namespace: {{ .Values.realworld.namespace}}*/}}
{{/*type: Opaque*/}}
{{/*data:*/}}
{{/*  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | printf "%v" | b64enc }}*/}}
{{/*  DATABASE_NAME: {{ .Values.secrets.DATABASE_NAME | printf "%v" | b64enc }}*/}}
{{/*  DATABASE_USER: {{ .Values.mysql.values.adminUsername | printf "%v" | b64enc }}*/}}
{{/*  DATABASE_PASSWORD: {{ .Values.mysql.values.adminPassword |  printf "%v" | b64enc }}*/}}
{{/*  DATABASE_HOST: {{ printf "mysql.%s.svc.cluster.local" .Values.mysql.namespace | b64enc }}*/}}
{{/*  DATABASE_PORT: {{ .Values.secrets.DATABASE_PORT | printf "%v" | b64enc }}*/}}
>>>>>>> 24eede954a135f9ec46abfcdb84ec964c50fd566

