apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name}} }-service
  namespace: {{ .Values.realworld.namespace | default "default"}}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.realworld.port }}
      targetPort: 8000
      nodePort: {{ .Values.realworld.nodePort }}
  type: NodePort
