apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.realworld.namespace | default "default"}}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    {{- with .Values.realworld.service}}
    - protocol: TCP
      port: {{ .port }}
      targetPort: 8000
    {{- end}}
  type: ClusterIP
