apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  sources:
    - path: chart/add-ons
      repoURL: https://github.com/the9thlime/realworldtt.git
      targetRevision: HEAD
      helm: {}
    - path: chart/realworld
      repoURL: https://github.com/the9thlime/realworldtt.git
      targetRevision: HEAD
      helm:
        releaseName: realworld
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
