apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    path: ./argocd-apps/base/ 
    repoURL: 'https://github.com/the9thlime/realworldtt/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
