apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: add-ons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/the9thlime/realworldtt.git
        revision: HEAD
        directories:
        - path: chart/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/the9thlime/realworldtt.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          releaseName: '{{.path.basename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
