FROM docker:latest

RUN apk update && \
    apk add openssh-agent \
    git \
    python3 \
    build-base && \
    mkdir -p ~/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
