apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS realworld;
    CREATE USER IF NOT EXISTS '{{ .Values.adminUsername }}'@'%' IDENTIFIED BY '{{ .Values.adminPassword }}';
    GRANT ALL PRIVILEGES ON realworld.* TO '{{ .Values.adminUsername }}'@'%';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
