{{- if .Values.jenkins.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  annotations:
    {{- if .Values.realworld.syncwave }}
    argocd.argoproj.io/sync-wave: "{{ .Values.realworld.syncwave }}"
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/the9thlime/realworldtt/'
    targetRevision: feat/helm-chart # Happy case
    path: add-ons/jenkins
    helm:
      value:
        installPlugins:
          - kubernetes:4253.v7700d91739e5
          - workflow-aggregator:600.vb_57cdd26fdd7
          - git:5.2.2
          - configuration-as-code:1836.vccda_4a_122a_a_e
          - docker-workflow:580.vc0c340686b_54
  destination:
    name: ''
    namespace: {{ .Values.jenkins.namespace | default "devops-tools" }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  {{- end }}