{{- if .Values.jenkins.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  annotations:
    {{- if .Values.realworld.syncwave }}
    argocd.argoproj.io/sync-wave: "{{ .Values.realworld.syncwave }}"
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: {{ .Values.jenkins.namespace | default "devops-tools" }}
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://github.com/the9thlime/realworldtt/'
    targetRevision: feat/helm-chart # Happy case
    path: add-ons/jenkins
    helm:
      value: |
        jenkins:
        {{ toYaml .Values.jenkins.values | nindent 10}}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  {{- end }}