apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realworld
  annotations: 
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/
    repoURL: 'https://github.com/the9thlime/realworldtt/'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
