apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: default
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWYzNSh4N3cjMWh6NyVvZWpjKHQoeDhpaTduXiVuMHB2enNwQHgqcXRmaDheJDNeM2or
  DATABASE_NAME: cmVhbHdvcmxk
  DATABASE_USER: cmVhbHdvcmxk
  DATABASE_PASSWORD: MTIz
  DATABASE_HOST: bXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  DATABASE_PORT: MzMwNg==

