apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworldtt-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: realworld
    app.kubernetes.io/instance: realworldtt
    app.kubernetes.io/part-of: realworldtt
    app.kubernetes.io/version: 0.0.6
    app.kubernetes.io/component: deployment
    app.kubernetes.io/managed-by:
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: realworld
  template:
    metadata:
      name: realworld
      labels:
        app.kubernetes.io/name: realworld
        app.kubernetes.io/instance: realworld
        app.kubernetes.io/part-of: realworldtt
        app.kubernetes.io/version: 0.0.6
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by:
    spec:
      containers:
        - name: realworldtt
          image: the9thlime/realworldtt:0.0.6
          ports:
            - containerPort: 8010
          resources:
            limits:
              cpu: 500m
              memory: 350Mi
            requests:
              cpu: 250m
              memory: 200Mi
          envFrom:
            - secretRef:
                name: django-secrets