apiVersion: v1
kind: Service 
metadata:
  name: realworld-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: realworld
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
