apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 1.11.1
    chart: ingress-nginx
    helm:
      valueFiles:
        - $values/values/values-ingress-nginx.yml
  - repoURL: 'https://github.com/the9thlime/realworldtt.git'
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
