apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: default
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWYzNSh4N3cjMWh6NyVvZWpjKHQoeDhpaTduXiVuMHB2enNwQHgqcXRmaDheJDNeM2or
  DATABASE_NAME: cmVhbHdvcmxk
  DATABASE_USER: cmVhbHdvcmxk
  DATABASE_PASSWORD: MTIz
  DATABASE_HOST: MTI3LjAuMC4x
  DATABASE_PORT: MzMwNg==

