apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworldtt-deployment
  namespace: devops-tools  # Ensure this matches the namespace in the Secret
  labels:
    app: realworldtt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: realworldtt
  template:
    metadata:
      labels:
        app: realworldtt
    spec:
      containers:
        - name: realworldtt
          image: the9thlime/realworldtt:0.0.22
          ports:
            - containerPort: 8010
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: SECRET_KEY
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_PORT
