apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mysql
    targetRevision: 8.8.8   # Replace with the desired version
    helm:
      values: |
        auth:
          rootPassword: MTIz
          database: cmVhbHdvcmxk
          username: cmVhbHdvcmxk
          password: MTIz
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

