{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-jenkins
  namespace: {{ .Values.global.argocd_namespace | default "argocd"}}
  annotations:
    {{- if .Values.istio.syncwave }}
    argocd.argoproj.io/sync-wave: {{ .Values.istio.syncwave | quote}}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL}}
    targetRevision: HEAD
    path: add-ons/istio
  destination:
    namespace: {{ .Values.istio.namespace }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  {{- end }}