{{- if .Values.jenkins.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-jenkins
  namespace: {{ .Values.global.argocd_namespace | default "argocd"}}
  annotations:
    {{- if .Values.jenkins.syncwave }}
    argocd.argoproj.io/sync-wave: {{ .Values.jenkins.syncwave | quote}}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL}}
    targetRevision: main
    path: add-ons/jenkins
    helm:
      releaseName: jenkins
      valueFiles:
        - values.yaml
  destination:
    namespace: {{ .Values.jenkins.namespace }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  {{- end }}