{{- if .Values.jenkins.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: {{ .Values.argocd.namespace | default "argocd"}}
  annotations:
    {{- if .Values.realworld.syncwave }}
    argocd.argoproj.io/sync-wave: {{ .Values.realworld.syncwave | quote}}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL}}
    targetRevision: HEAD
    path: add-ons/jenkins
    helm: {}
  destination:
    name: ''
    namespace: {{ .Values.jenkins.namespace | default "devops-tools" }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  {{- end }}