{{- if .Values.kube_prometheus_stack.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-kube-prometheus-stack
  namespace: {{ .Values.global.argocd_namespace | default "argocd"}}
  annotations:
    {{- if .Values.kube_prometheus_stack.syncwave }}
    argocd.argoproj.io/sync-wave: {{ .Values.kube_prometheus_stack.syncwave | quote}}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL}}
    targetRevision: main
    path: add-ons/kube-prometheus-stack
  destination:
    namespace: {{ .Values.kube_prometheus_stack.namespace }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
