mysqlRootPassword: "123"
mysqlRealworldPassword: "123"
mysql:
  primary:
    extraVolumes:
      - name: init-script
        configMap:
          name: mysql-init-script
    extraVolumeMounts:
      - name: init-script
        mountPath: /docker-entrypoint-initdb.d/init.sql
        subPath: init.sql
        readOnly: true

  auth:
    createDatabase: false
    existingSecret: mysql-root-password
