auth:
  rootPassword: "123"
  createDatabase: false
initdbScripts:
  init.sql: |
    CREATE DATABASE realworld;
    CREATE USER 'realworld'@'%' IDENTIFIED BY '123';
    GRANT ALL PRIVILEGES ON realworld.* TO 'realworld'@'%';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;