apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realworld
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./k8s/
    repoURL: 'https://github.com/the9thlime/realworldtt/'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

