##############################
# Global values
##############################
global:
  argocd_namespace: argocd
  repoURL: https://github.com/the9thlime/realworldtt.git

###############################
# Add-ons
###############################
jenkins:
  enabled: true
  syncwave:
  namespace: devops-tools

kubePrometheusStack:
  enabled: true
  syncwave:
  namespace: monitoring

minio:
  enabled: true
  nameOverride:
  syncwave:
  namespace: minio
  persistence:
    enabled: true
    existing
  resources:
    requests:
      memory:
  buckets: []
    #   # Name of the bucket
    # - name: bucket1
    #   # Policy to be set on the
    #   # bucket [none|download|upload|public]
    #   policy: none
    #   # Purge if bucket exists already
    #   purge: false
    #   # set versioning for
    #   # bucket [true|false]
    #   versioning: false # remove this key if you do not want versioning feature
    #   # set objectlocking for
    #   # bucket [true|false] NOTE: versioning is enabled by default if you use locking
    #   objectlocking: false
  users:
    - accessKey:
      existingSecret:
      existingSecretKey:
  policies:
